### ISSUE TITLE
Way to contribute?

### ISSUE THREAD

**Issue by MrBlenny** [blacha/diablo2#149]
@blacha very very cool!!! 
I look forward to it seeing it work with D2R. 

If there is some way I can contribute I'd be very happy to help.

I imagine there are lots of other things to do but I was thinkin' it could be nice to build out the frontend a little more. Maybe [react-map-gl](https://github.com/visgl/react-map-gl) (which plays nice with map-libre) and build out a bit more UI in React?

**Comment by blacha** [comment]
Howdy, any contribution is welcome!

Since D2R's map generation is the same as diablo2 classic, it sort of works now, if you can find the map seed from the d2r client you can generate the maps and use them.

the `@diablo2/memory` package has an example of this working under linux only though..

In terms of the front end, there is a bunch of information returned from the map process like which tomb is the correct tomb, summoner location, way points, shrines, wells. It would be cool to add those onto the map somehow.

Right now the map is made up of a canvas "raster" layer https://github.com/blacha/diablo2/blob/master/packages/map/src/viewer/map.ts#L82 It would be cool to add these other features as a vector layer 

The frontend UI was hacked together super quickly so I'm not attached to it at all, if you wanted to bring in something like react that would be a ok with me.

**Comment by pastuh** [comment]
Somehow no proper guide how to use for D2R.
At this moment I just get errors ..
Example: 
`root@3008c2adfacb:/app# wine bin/d2-map.exe game --seed 10 --level 1 --difficulty 0
{"level":30,"time":1635967935099,"source":"map/main.c:91","msg":"Cli:Start","version":"v0.9.0-12-g1dcc","hash":"1dcc7cc5586d4b60bc50267dcc2bf55225603958"}
{"level":20,"time":1635967935152,"source":"map/main.c:124","msg":"Cli:Arg","game":"game"}
{"level":20,"time":1635967935172,"source":"map/main.c:105","msg":"Cli:Arg","seed": "0x00000a"}
{"level":20,"time":1635967935196,"source":"map/main.c:124","msg":"Cli:Arg","game":"--level"}
{"level":20,"time":1635967935219,"source":"map/main.c:124","msg":"Cli:Arg","game":"1"}
{"level":20,"time":1635967935251,"source":"map/main.c:109","msg":"Cli:Arg","difficulty":0}
{"level":20,"time":1635967935333,"source":"map/d2_client.c:147","msg":"Init:Dll","path":"1"}
{"level":50,"time":1635967935372,"source":"map/d2_client.c:151","msg":"Init:Failed:UnknownGameVersion","path":"1"}`



`docker run -v "/C/Games/Diablo":/app/game -p 8899:8899 docker.io/blacha/diablo2:latest
{"level":30,"time":1635968062212,"pid":1,"hostname":"5a6f29a583b2","id":"01fkkmq4nhme49e5wwj1e1wv3w","url":"/health","msg":"Bind"}
{"level":30,"time":1635968062213,"pid":1,"hostname":"5a6f29a583b2","id":"01fkkmq4nhme49e5wwj1e1wv3w","url":"/v1/map/:seed/:difficulty.json","msg":"Bind"}
{"level":30,"time":1635968062214,"pid":1,"hostname":"5a6f29a583b2","id":"01fkkmq4nhme49e5wwj1e1wv3w","url":"/v1/map/:seed/:difficulty/:act.json","msg":"Bind"}
{"level":30,"time":1635968062214,"pid":1,"hostname":"5a6f29a583b2","id":"01fkkmq4nhme49e5wwj1e1wv3w","url":"/v1/map/:seed/:difficulty/:act/:level.json","msg":"Bind"}
{"level":30,"time":1635968062214,"pid":1,"hostname":"5a6f29a583b2","id":"01fkkmq4nhme49e5wwj1e1wv3w","url":"/v1/map/:seed/:difficulty/:level.png","msg":"Bind"}
{"level":30,"time":1635968062218,"pid":1,"hostname":"5a6f29a583b2","id":"01fkkmq4nhme49e5wwj1e1wv3w","port":8899,"processes":1,"version":"v0.9.0-12-g1dcc","hash":"1dcc7cc5586d4b60bc50267dcc2bf55225603958","msg":"Server started..."}
[Error: ENOENT: no such file or directory, open '/app/game/patch_d2.mpq'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/app/game/patch_d2.mpq'
}`

**Comment by blacha** [comment]
@pastuh this should be a separate issue, 

The getting started guide has how to install and run the map server using a diablo2 classic client https://github.com/blacha/diablo2/tree/master/packages/map#getting-started

D2R uses the same map generation logic so you just need to extract the current map seed. This library does not help with this.
